### PR TITLE
video_player_page to master branch

### PR DESCRIPTION
**Pull request by glowreeyah**
## Youtube Clone : Embedding images and video

In this project we:
- inputted a navigation bar with icons
- embedded a video with its description and comments
- used images in the side bar to as a replica for recommended videos.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @glowreeyah, @Hermela-Fikre. You have an impressive first project :+1:. Let's now take care of the following:arrow_forward:**

1. The width of your search bar is smaller than the original. Consider increasing it a bit.

2. You have validation errors in your html. Validate your html [here](https://validator.w3.org/#validate_by_upload) and fix all errors. 

3. Stickler is not required for this particular project. Since you have not been able to make your tests pass, it is better to disable stickler for this repository and remove the linter files from the project folder.

4. **Optional:** You should rename this repository to identify the project properly. **'Youtube Clone'** is a better repo name. You may have to re-clone your project to your local machine after renaming to be able to push to it properly.

_**Kindly address the above and submit another code review request. Note that you don't have to open another pull request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but you haven't implemented required changes by the previous reviewer.Let's do that. 

### Make changes and submit another code review request.
*Happy coding*

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### Good job so far :clap: However, you have a few changes to work on before your project could be approved.
- On the sidebar, use video thumbnails instead of image thumbnails

### [OPTIONAL]
- Always try to use html5 semantics, `article, nav, section, aside, footer, main` properly, you can refactor your code to match these standards

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### Good job :clap: Having implemented previous reviews, your project looks good and I approve of it. Congratulations :boom: :100:
### You can now merge to master and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
